# Generated by Django 4.2.7 on 2023-12-30 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BOOKS_TBL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ISBN', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('authors', models.CharField(max_length=60)),
                ('books', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ORDERS_TBL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('ISBN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codes', to='login.books_tbl')),
                ('order_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='login.books_tbl')),
            ],
        ),
    ]
